---
output: 
  html_document:
    code_folding: hide
self_contained: yes
---
  
```{r setup, message = F, warning = F, results = 'hide', echo = F}
knitr::opts_chunk$set(echo = T, warning = F, message = F, fig.path = 'figs/', dev.args = list(family = 'serif'))
```

# Declustering

```{r, message = F, warning = F}
library(tidyverse)
library(here)
library(lubridate)
library(ggExtra)
library(gridExtra)
library(extRemes)

# import data
indvar0 <- read.csv(here::here('data/data-raw/LR_final_indvar0.csv'), stringsAsFactors = F)

# rename and format date
dat <- indvar0 %>% 
  select(
    date = stime0,
    precp = `indvar0...1.`,
    water = `indvar0...3.`
  ) %>% 
  mutate(date = dmy(date))
```

## Declustering precip only {.tabset}

### > 3 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 3
dcldat <- dat %>% 
  mutate(
    fltval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(fltval))
  ) %>% 
  filter(precp > fltval)

p1 <- ggplot(dcldat, aes(x = water, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```

### > 4 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 4
dcldat <- dat %>% 
  mutate(
    fltval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(fltval))
  ) %>% 
  filter(precp > fltval)

p1 <- ggplot(dcldat, aes(x = water, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```

### > 5 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 5
dcldat <- dat %>% 
  mutate(
    fltval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(fltval))
  ) %>% 
  filter(precp > fltval)

p1 <- ggplot(dcldat, aes(x = water, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```

## Declustering precip and water {.tabset}

### > 3 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 3
dcldat <- dat %>% 
  mutate(
    prcval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(prcval)),    
    wtrval = mean(water, na.rm = T) + sdup * sd(water, na.rm = T),
    dclwater = decluster(water, unique(wtrval))
  ) %>% 
  filter(precp > prcval)

p1 <- ggplot(dcldat, aes(x = dclwater, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```

### > 4 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 4
dcldat <- dat %>% 
  mutate(
    prcval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(prcval)),    
    wtrval = mean(water, na.rm = T) + sdup * sd(water, na.rm = T),
    dclwater = decluster(water, unique(wtrval))
  ) %>% 
  filter(precp > prcval)

p1 <- ggplot(dcldat, aes(x = dclwater, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```

### > 5 sd

```{r, fig.height = 5, fig.width = 10}
sdup <- 5
dcldat <- dat %>% 
  mutate(
    prcval = mean(precp, na.rm = T) + sdup * sd(precp, na.rm = T),
    dclprecp = decluster(precp, unique(prcval)),    
    wtrval = mean(water, na.rm = T) + sdup * sd(water, na.rm = T),
    dclwater = decluster(water, unique(wtrval))
  ) %>% 
  filter(precp > prcval)

p1 <- ggplot(dcldat, aes(x = dclwater, y = dclprecp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma~'declustered')
  )

p2 <-  ggplot(dcldat, aes(x = water, y = precp)) +
  geom_path(color = 'grey') + 
  geom_point(size = 2) + 
  theme_bw() + 
  theme(
    panel.grid = element_blank()
  ) +
  labs(
    x = expression(paste(W[2], ' (m, MLLW)')), 
    y = expression(paste(P[2], ' (cm)')), 
    title = bquote('Values >'~.(sdup)*sigma)
  )

p1 <- ggMarginal(p1, type = 'histogram', size = 2)
p2 <- ggMarginal(p2, type = 'histogram', size = 2)
grid.arrange(p1, p2, ncol = 2)
```