---
title: "SSO risk probabilities"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---
  
```{r, warning = F, message = F, echo = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F)

library(shiny)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(ShinyDash)
library(shinydashboard)
library(flexdashboard)
# library(plotly)

data(indvar0)
data(rskmod)

source("R/funcs.R")

alph <- 0.8
dts <- range(indvar0$date)

downloadButtonRmd <- function (outputId, label = "Download", class = NULL, ...)  {
  tags$a(id = outputId, class = paste("btn btn-default shiny-download-link", 
                                      class), href = "", target = "_blank", download = NA, 
         icon("download"), label, ...)
}
```

```{r reactives}
# predictions
prds <- reactive({
  
  # inputs
  dtssel <- input$dtssel
  wtrsel <- input$wtrsel
  prpsel <- input$prpsel
  prbsel <- input$prbsel
  
  out <- hindcastSSO(dtssel[1], dtssel[2], wtrsel, prpsel, indvar0, rskmod, prbsel)
  
  return(out)
  
})

# estimate number of events
evnts <- reactive({
  
  # inputs
  prds <- prds()
  
  out <- rle(prds$evnt)
  out <- out$lengths[out$value]
  out <- length(out)
  
  return(out)

})

# estimate total length of events
lens <- reactive({
  
  # inputs
  prds <- prds()
  
  out <- rle(prds$evnt)
  out <- out$lengths[out$value]
  out <- sum(out)
  
  return(out)

})

# plot
plos <- reactive({
  
  # input
  prds <- prds()
  prbsel <- input$prbsel
  
  toplo <- prds
  
  p1 <- ggplot(toplo, aes(x = date, ymax = risk)) + 
    geom_ribbon(aes(ymin = 0), fill = 'tomato1', alpha = alph) + 
    # geom_line(aes(y = risk), color = 'tomato1') +
    theme_bw(base_size = 18) + 
    scale_y_continuous(limits = c(0, 1), expand = c(0, 0)) + 
    scale_x_date(expand = c(0, 0)) +
    geom_hline(yintercept = prbsel, linetype = 'dashed', size = 1) + 
    labs(
      x = NULL, 
      y = 'Pr. overflow'
    )
  
  p2 <- ggplot(toplo, aes(x = date, ymax = water)) + 
    geom_ribbon(aes(ymin = 0), alpha = alph, fill = 'lightblue') +
    # geom_line(aes(y = water), color = 'lightblue') +
    theme_bw(base_size = 18) + 
    scale_y_continuous(limits = c(0, 2.02), expand = c(0, 0)) + 
    scale_x_date(expand = c(0, 0)) +
    labs(
      x = NULL, 
      y = '2-day max water (m)'
    )
  
  p3 <- ggplot(toplo, aes(x = date, ymax = precp)) + 
    geom_ribbon(aes(ymin = 0), alpha = alph, fill = 'grey') + 
    # geom_line(aes(y = precp), color = 'grey') +
    theme_bw(base_size = 18) + 
    scale_x_date(expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 10.5), expand = c(0, 0)) + 
    labs(
      x = NULL, 
      y = '2-day precip (cm)'
    )

  out <- p1 + p2 + p3 + plot_layout(ncol = 1)
  
  return(out)
  
})
```

```{r downloadhandlers}
# risk predictions
output$rskdwntab <- downloadHandler(
  filename = function(){'riskdat.csv'},
  content = function(file){
    todl <- prds()
    write.csv(todl, file, quote = T, row.names = F)
  }
)
```

```{r ui}
column(12, 
  column(3, 
    sliderInput('dtssel', 'Select date range:', min = dts[1], max = dts[2], value = dts, timeFormat="%Y-%m", width = '600px')
  ),       
  column(3, 
    sliderInput('prbsel', 'Select probability defining SSO:', min = 0, max = 1, value = 0.4, width = '600px', animate = T)
  ),
  column(3, 
    sliderInput('wtrsel', 'Select 2-day max water increase (m):', min = 0, max = 0.5, value = 0.3, width = '600px', animate = T)
  ),
  column(3, 
    sliderInput('prpsel', 'Select 2d-precipitation increase (cm):', min = 0, max = 1.8, value = 0.2, width = '600px', animate = T)
  )
)
column(12, 
       column(4, 
              downloadButtonRmd('rskdwntab', 'Download data')
              )
)
```

Row {data-height=100}
-------------------------------------

###   
   
```{r}
output$evntsbox <- renderValueBox({
  
  # input
  evnts <- evnts()
  
  flexdashboard::valueBox(
    evnts, "Overflow events", color = "lightblue"
  )

})
valueBoxOutput('evntsbox')
```

###

```{r}
output$lensbox <- renderValueBox({
  
  # input
  lens <- lens()
  
  valueBox(
    lens, "Overflow total duration in days", color = "lightblue"
  )

})
valueBoxOutput('lensbox')
```

###

```{r}
output$percbox <- renderValueBox({
  
  # input
  lens <- lens()
  dtssel <- input$dtssel
  
  tots <- diff(dtssel, units = 'days')
  tots <- as.numeric(tots)
  perc <- paste(round(100 * lens / tots, 1), '%')

  valueBox(
    perc, "Overflow total duration in percent", color = "lightblue"
  )

})
valueBoxOutput('percbox')
```

Row {data-height=650}
-------------------------------------

### 

```{r}
output$plos <- renderPlot(plos())
plotOutput('plos')
```

